### ISSUE TITLE
Try to Add New Branch To Push Code One From another 

### ISSUE THREAD

**Issue by saurabhdindokar** [sakshigawande16/PRODIGY_WD_05#1]
Hello Sakshi, Everything  is good ....i Just checkout your branches ..there was only one branch named Main ..mu suggestion is to add few mode sub branches like prod, preprod, dev and then pull and push code one by one from dev to preprod then preprod to prod then prod to main....as per this procedure is mandatory in future in industry level

**Comment by sakshigawande16** [comment]
Hello,
can you pls introduced yourself

**Comment by saurabhdindokar** [comment]
Here is Saurabh..LinkedIn connection
